version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  php:
    build: ./infra/php
    volumes:
      - ./infra/php/php.ini:/usr/local/etc/php/php.ini
      - ./app/src:/var/www/src
      - ./app/vendor:/var/www/vendor
      - ./app/web:/var/www/html
    environment:
      - VIRTUAL_HOST=web.localhost
      - DB_HOST=mysql
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
  composer:
      image: composer
      command: "composer install"
      volumes:
        - ./:/app
  mysql:
    image: mysql:5.7
    volumes:
      - ./infra/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
  adminer:
    image: adminer
    restart: always
    environment:
      - VIRTUAL_HOST=adminer.localhost
