version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  php:
    image: php:8.1-apache
    volumes:
      - ./assets/php.ini:/usr/local/etc/php/php.ini
      - ./app/httpdocs:/var/www/html
    environment:
      - VIRTUAL_HOST=web.localhost
  composer:
      image: composer
      command: "composer install"
      volumes:
        - ./app/src:/app
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=test
      - PMA_PASSWORD=test
      - VIRTUAL_HOST=phpmyadmin.localhost
